# Generated by Django 2.2.24 on 2021-07-19 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='VideoContentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('video', models.FileField(upload_to=home.utils.get_upload_path, verbose_name='Video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video_content_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('video_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_content_comments', to='video_content.VideoContent', verbose_name='Vodeo Content')),
            ],
            options={
                'verbose_name': 'Video Content Comment',
                'verbose_name_plural': 'Video Content Comments',
            },
        ),
    ]
