# Generated by Django 2.2.24 on 2021-06-29 20:04

from django.db import migrations, models
import home.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=home.utils.get_upload_path, verbose_name='Profile Picture'),
        ),
    ]
